/control/suppressAbortion 1 

/samurai/geometry/Dipole/Angle 30 deg
/samurai/geometry/Dipole/FieldFile /home/kondo/exp/samurai/field_map/120405-bn_stage-d-540,0A-3,0T-map.bin
/samurai/geometry/Dipole/FieldFactor 1.0

/samurai/geometry/NEBULA/ParameterFileName geometry/NEBULA_samurai21_8.csv
/samurai/geometry/NEBULA/DetectorParameterFileName geometry/NEBULA_Detectors_samurai21_8.csv

/samurai/geometry/NeuLAND/ParameterFileName geometry/NeuLAND_samurai21_8.csv
/samurai/geometry/NeuLAND/DetectorParameterFileName geometry/NeuLAND_Detectors_samurai21_8.csv

/samurai/geometry/Target/Position 0 0 -4500 mm

# must be called after definition of detector positions
/samurai/geometry/Update

/action/file/RunName samurai21_8_1n_
/action/file/SaveDirectory root/storage/
/action/file/OverWrite y

/action/data/NEBULA/StoreSteps false
/action/data/NeuLAND/StoreSteps false

# do not include resolution
#/action/data/NeuLAND/Resolution false
#/action/data/NEBULA/Resolution false

/action/gun/Type Gaus
/action/gun/Position 0 0 -4500 mm
/action/gun/PositionXSigma 10 cm
/action/gun/PositionYSigma 10 cm
/action/gun/AngleXSigma 40 mrad
/action/gun/AngleYSigma 40 mrad

/action/gun/Z 0
/action/gun/A 1
/action/gun/SetBeamParticle
/action/gun/Energy 240 MeV

/run/beamOn 1000000

