#
# to avoid run stop originated from G4Exception
/control/suppressAbortion 1

/samurai/geometry/Dipole/Angle 30 deg
/samurai/geometry/Dipole/FieldFile /home/kondo/exp/samurai/field_map/120405-bn_stage-d-540,0A-3,0T-map.bin
/samurai/geometry/Dipole/FieldFactor 1.0

/samurai/geometry/NEBULA/ParameterFileName geometry/NEBULA_samurai21_3.csv
/samurai/geometry/NEBULA/DetectorParameterFileName geometry/NEBULA_Detectors_samurai21_3.csv

/samurai/geometry/NeuLAND/ParameterFileName geometry/NeuLAND_samurai21_3.csv
/samurai/geometry/NeuLAND/DetectorParameterFileName geometry/NeuLAND_Detectors_samurai21_3.csv

/samurai/geometry/Target/Position 0 0 -4500 mm

/samurai/geometry/FillAir false

# must be called after definition of detector positions
/samurai/geometry/Update

/action/file/RunName samurai21_3_28o_seq_small_
/action/file/SaveDirectory root/storage/
/action/file/OverWrite y

/action/data/NEBULA/StoreSteps false
/action/data/NeuLAND/StoreSteps false

/action/gun/Type Tree 

/action/gun/tree/InputFileName root/storage/inputtree_28o_seqdecay_0.05_0.02.root
/action/gun/tree/TreeName tree_input
/action/gun/tree/beamOn 0

/action/gun/tree/InputFileName root/storage/inputtree_28o_seqdecay_0.1_0.02.root
/action/gun/tree/TreeName tree_input
/action/gun/tree/beamOn 0
