#
# to avoid run stop originated from G4Exception
/control/suppressAbortion 1

/samurai/geometry/Dipole/Angle 30 deg
/samurai/geometry/Dipole/FieldFile /home/kondo/exp/samurai/field_map/120405-bn_stage-d-540,0A-3,0T-map.bin
/samurai/geometry/Dipole/FieldFactor 1.0

/samurai/geometry/NEBULA/ParameterFileName geometry/NEBULA_samurai21_6.csv
/samurai/geometry/NEBULA/DetectorParameterFileName geometry/NEBULA_Detectors_samurai21_6.csv

/samurai/geometry/NeuLAND/ParameterFileName geometry/NeuLAND_samurai21_6.csv
/samurai/geometry/NeuLAND/DetectorParameterFileName geometry/NeuLAND_Detectors_samurai21_6.csv

/samurai/geometry/Target/Position 0 0 -4000 mm

/samurai/geometry/FillAir false

# must be called after definition of detector positions
/samurai/geometry/Update

/action/file/RunName samurai21_6_25o_ps_
/action/file/SaveDirectory root/storage/
/action/file/OverWrite y

/action/data/NEBULA/StoreSteps false
/action/data/NeuLAND/StoreSteps false

/action/gun/Type Tree 

/action/gun/tree/InputFileName root/storage/inputtree_25o_psdecay_4000_0.5.root
/action/gun/tree/TreeName tree_input
/action/gun/tree/beamOn 10000

/action/gun/tree/InputFileName root/storage/inputtree_25o_psdecay_4000_1.root
/action/gun/tree/TreeName tree_input
/action/gun/tree/beamOn 10000

/action/gun/tree/InputFileName root/storage/inputtree_25o_psdecay_4000_2.root
/action/gun/tree/TreeName tree_input
/action/gun/tree/beamOn 10000

/action/gun/tree/InputFileName root/storage/inputtree_25o_psdecay_4000_3.root
/action/gun/tree/TreeName tree_input
/action/gun/tree/beamOn 10000

/action/gun/tree/InputFileName root/storage/inputtree_25o_psdecay_4000_4.root
/action/gun/tree/TreeName tree_input
/action/gun/tree/beamOn 10000

/action/gun/tree/InputFileName root/storage/inputtree_25o_psdecay_4000_5.root
/action/gun/tree/TreeName tree_input
/action/gun/tree/beamOn 10000

/action/gun/tree/InputFileName root/storage/inputtree_25o_psdecay_4000_6.root
/action/gun/tree/TreeName tree_input
/action/gun/tree/beamOn 10000

/action/gun/tree/InputFileName root/storage/inputtree_25o_psdecay_4000_7.root
/action/gun/tree/TreeName tree_input
/action/gun/tree/beamOn 10000

/action/gun/tree/InputFileName root/storage/inputtree_25o_psdecay_4000_8.root
/action/gun/tree/TreeName tree_input
/action/gun/tree/beamOn 10000

/action/gun/tree/InputFileName root/storage/inputtree_25o_psdecay_4000_9.root
/action/gun/tree/TreeName tree_input
/action/gun/tree/beamOn 10000

